---
- hosts: all
  name: Setup common task in all servers
  gather_facts: true
  become: true

  vars:
    repo: "https://github.com/senin24/home-lab.git"
    dest: "/home/{{ ansible_user }}/home-lab"
    branch: "develop"

    share_name: myshare
    share_path: /srv/myshare
    share_permissions: "rw,user=user1"

  tasks:
    - name: SSH tasks
      ansible.builtin.import_tasks: tasks/ssh.yml

    - name: Base Configuration
      ansible.builtin.import_tasks: tasks/base.yml

    - name: Docker-compose install
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Docker-compose UP
      ansible.builtin.import_tasks: tasks/docker_compose_up.yml

    # # Start All Docker Containers
    # - import_tasks: containers/start-containers.yml
    # # Stop All Docker Containers
    # - import_tasks: containers/stop-containers.yml
    # # Remove All Docker Containers
    # - import_tasks: containers/remove-containers.yml

    # # Deploy Security (Docker)
    # - import_tasks: containers/deploy-endlessh.yml
    # - import_tasks: containers/deploy-traefik_network.yml
    # - import_tasks: containers/deploy-traefik.yml
    # # Deploy Essential Containers (Docker)
    # - import_tasks: containers/deploy-homer.yml
    # - import_tasks: containers/deploy-vaultwarden.yml
    # - import_tasks: containers/deploy-portainer.yml
    # - import_tasks: containers/deploy-duplicati.yml
    # - import_tasks: containers/deploy-syncthing.yml
