- name: Main playbook
  hosts: all
  become: true

  tasks:
    - name: Update
    # Base Configuration
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/docker.yml

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - zsh
          - htop
          - git
          - docker.io
          - docker-conpose
