- name: Install Podman
  apt:
    name: 
      - podman
    update_cache: yes

- name: Update Packages (Debian-Based)
  apt:
    update_cache: yes
    upgrade: yes

- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  become_user: "{{ lookup('env','USER') }}"
  pip:
    name:
      - podman-compose
